# Generated by Django 5.0.2 on 2024-03-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spent',
            old_name='votes',
            new_name='mount',
        ),
        migrations.RemoveField(
            model_name='spent',
            name='choice_text',
        ),
    ]
